image: docker.slock.it/build-images/node:10-alpine
stages:
  - build
  - package
  - deploy

build-backend:
  stage: build
  tags:
    - short-jobs
  script:
    - sh /prepare.sh
    - npm install
    - npm install -g typescript
    - tsc
  artifacts:
      name: build
      paths:
        - build/
        - node_modules/

package-into-docker:
  image: docker
  stage: package
  dependencies:
    - build-backend
  tags:
    - short-jobs
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE:latest


.deploy-tmpl:
  stage: deploy
  except:
    - branches
  tags:
    - short-jobs
  image: docker.slock.it/build-images/deployment
  services:
    - docker:dind
  dependencies:
      - package-into-docker
  script:
    - cd deployment
    - rancher -w up -d --prune -p -s voting-backend-${TARGET} -c --force-upgrade
    - sentry-cli releases new -p voting-backend voting-backend@${CI_COMMIT_REF_NAME}
    - sentry-cli releases deploys voting-backend@${CI_COMMIT_REF_NAME} new -e ${TARGET}
    - sentry-cli releases set-commits --auto voting-backend@${CI_COMMIT_REF_NAME}


deploy-to-production:
    extends: .deploy-tmpl
    only:
      - /^v[0-9]+.[0-9]+.[0-9]+$/
    variables:
      TARGET: production
      CI_DBNAME: voting_goerli
      CI_CONTRACT: '0xa603eed441b3f6d0a9143f846be6896de10318a3'
      CI_RPC: 'http://lb.parity-rpc/goerli'

deploy-to-stage:
    extends: .deploy-tmpl
    only:
      - /^v[0-9]+.[0-9]+.[0-9]+-(alpha|beta|rc)\.[0-9]+$/
    variables:
      TARGET: stage
      CI_DBNAME: voting
      CI_CONTRACT: '0xa603eed441b3f6d0a9143f846be6896de10318a3'
      CI_RPC: 'http://lb.parity-rpc/mainnet'
    






