image: docker.slock.it/build-images/node:10-alpine
stages:
  - build
  - test
  - package
  - deploy

build-backend:
  stage: build
  tags:
    - short-jobs
  script:
    - sh /prepare.sh
    - npm install
    - npm install -g typescript
    - tsc
  artifacts:
      name: build
      paths:
        - build/
        - node_modules/

test-backend:
  stage: test
  tags:
    - short-jobs
  script:
    - sh /prepare.sh
    - npm install
    - npm test

package-into-docker:
  image: docker
  stage: package
  dependencies:
    - build-backend
  tags:
    - short-jobs
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE:latest

deploy-to-production:
    stage: deploy
    tags:
      - short-jobs
    only:
      - tags
    image: markuskeil/docker-and-rancher
    dependencies:
      - package-into-docker
    services:
      - docker:dind
    script:
      - rancher-compose -p $CI_PROJECT_PATH_SLUG up -p -d -c --force-upgrade




