version: '2'
services:
  backend:
    image: docker.slock.it/blockchain-voting/voting-backend:$CI_COMMIT_REF_NAME
    environment:
      MONGO_URL: mongodb://10.142.1.25:27017
      MONGO_NAME: $CI_DBNAME
      CONTRACT_ADDR: $CI_CONTRACT
      RPC_URL: $CI_RPC,
      VERSION: $CI_COMMIT_REF_NAME,
      TARGET: $TARGET
      SIGNPK: $CI_SIGNPK
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: role=application
