version: '2'
services:
  backend-mainnet:
    image: docker.slock.it/blockchain-voting/voting-backend:$CI_COMMIT_REF_NAME
    environment:
      MONGO_URL: mongodb://10.142.1.15:27017
      MONGO_NAME: $CI_DBNAME_MAIN
      MONGO_DATANAME: voting
      CONTRACT_ADDR: '0xa603eed441b3f6d0a9143f846be6896de10318a3'
      RPC_URL: https://rpc.slock.it/mainnet
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: role=application
  backend-tobalaba:
    image: docker.slock.it/blockchain-voting/voting-backend:$CI_COMMIT_REF_NAME
    environment:
      MONGO_URL: mongodb://10.142.1.15:27017
      MONGO_NAME: $CI_DBNAME_TOB
      MONGO_DATANAME: voting_tobalaba
      RPC_URL: https://rpc.slock.it/tobalaba
      CONTRACT_ADDR: '0x20bac229d6280a0ef79b2dc472b0c0113d2b993f'
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: role=application